## Visualização Interativa de Dados Geográficos 

# Folium

* Documentação no GitHub - https://python-visualization.github.io/folium/latest/

In [72]:
import pandas as pd
import geopandas as gpd
import folium

In [6]:
# ler arquivos Countries
countries = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))

# Ler arquivo Acled 
acled = gpd.read_file(
    r'C:\Users\iribarre\Downloads\5-+Interactive+Visualization\data\acled2019.shp',
    mask = countries[countries['continent'] == 'South America']
)

In [7]:
acled.head()

data_id  iso event_id_c  event_id_n        event_date  year  time_preci  \
0  6947603   76   BRA10737       10737  31 December 2019  2019           2   
1  6966548   76   BRA10732       10732  31 December 2019  2019           1   
2  6938394  170    COL1824        1824  31 December 2019  2019           2   
3  6953510   32    ARG1263        1263  31 December 2019  2019           1   
4  6931761  152    CHI2724        2724  31 December 2019  2019           1   

                   event_type        sub_event_  \
0  Violence against civilians            Attack   
1                     Battles       Armed clash   
2      Strategic developments             Other   
3                    Protests  Peaceful protest   
4                    Protests  Peaceful protest   

                                              actor1  ... latitude  longitude  \
0            Unidentified Gang and/or Police Militia  ...  -8.0694   -37.2684   
1  Military Forces of Brazil (2019-) Military Police  ...  -3.1019   -60.0250   
2                Unidentified Armed Group (Colombia)  ...   7.7872   -75.5331   
3                             Protesters (Argentina)  ... -31.9745   -60.9160   
4                                 Protesters (Chile)  ... -41.4693   -72.9424   

  geo_precis                  source   source_sca  \
0          1                      G1     National   
1          1       Portal do Holanda     National   
2          2           El Espectador     National   
3          1  La Capital (Argentina)  Subnational   
4          1            Biobio Chile     National   

                                               notes fatalities   timestamp  \
0  On 30 December 2019, in Sertania, Pernambuco, ...          1  1582840217   
1  On 31 December 2019, in Manaus, Amazonas, two ...          2  1582840367   
2  As reported on December 31 2019, between La Ca...          0  1582839943   
3  On 31 December 2019, in Coronda (Santa Fe), a ...          0  1582840236   
4  On 31 December 2019, in Puerto Montt, Los Lago...          0  1582839796   

  iso3                     geometry  
0  BRA   POINT (-37.26840 -8.06940)  
1  BRA   POINT (-60.02500 -3.10190)  
2  COL    POINT (-75.53310 7.78720)  
3  ARG  POINT (-60.91600 -31.97450)  
4  CHL  POINT (-72.94240 -41.46930)  

[5 rows x 32 columns]

In [11]:
# Use o folium para localizar uma coordanada no Map street Maps
m= folium.Map(location=[-23.6100596,-46.6973898])
m

Visualização de um ponto específico no mapa

In [29]:
# Adicione zoom. Quanto menor o número, mais distante. 
m= folium.Map(location=[-23.6100596,-46.6973898], zoom_start=15)
m

In [31]:
# Mude a base do mapa
m= folium.Map(location=[-23.6100596,-46.6973898], tiles='CartoDB dark_matter', zoom_start=15)
m

In [33]:
# Adicione um marcador na localização específica
folium.Marker(
    location=[-23.6100596,-46.6973898],
    radius=25,
    popup='Anfield Stadium',
    color='crimson',
    fill=True
).add_to(m)
m

In [36]:
# Adicione texto no marcador
folium.Marker(
    location=[-23.6100596,-46.6973898],
    popup='<i>HERE São Paulo</i>'
).add_to(m)
m

In [37]:
# Adicione um marcador em círculo
folium.Circle(
    location=[-23.6100596,-46.6973898], 
    radius=25,
    popup='HERE São Paulo',
    color='crimson', 
    fill=True,
).add_to(m)
m

Visualização do arquivo Acled

In [42]:
# Visualização direta a partir do geopandas/geojson
m = folium.Map([-23.6100596,-46.6973898], zoom_start=2, tites='cartodbpositron')
folium.GeoJson(acled.sample(1000)).add_to(m)
m

In [57]:
m = folium.Map([-23.6100596,-46.6973898], zoom_start=2, titles='cartodbpositron')
acled_sample = acled.sample(100)
locs_points = zip(acled_sample.geometry.y, acled_sample.geometry.x)
for location in locs_points:
    folium.CircleMarker(location=location, color='red', radius=0.5).add_to(m)
m

In [52]:
# Importe nova biblioteca
from folium.plugins import FastMarkerCluster 

# Visualizar map em cluster (conjunto)
cmap = folium.Map(location=[-23.6100596,-46.6973898],
                 zoom_start=2,
                  tiles='CartoDB dark_matter')

# Criação de um mapa de clusters a partir de uma lista de coordenadas, alterando a visualização de acordo com o zoom
FastMarkerCluster(data=list(zip(acled_sample.geometry.y.values, acled_sample.geometry.x.values))).add_to(cmap)
folium.LayerControl().add_to(cmap)
cmap

In [58]:
# Importar bibliotecas para visualizar heatmap
from folium.plugins import HeatMap, HeatMapWithTime

In [59]:
# Seleciona apenas as colunas de latitude e longitude do dado
df = acled[['latitude', 'longitude']]
df.head()

latitude  longitude
0   -8.0694   -37.2684
1   -3.1019   -60.0250
2    7.7872   -75.5331
3  -31.9745   -60.9160
4  -41.4693   -72.9424

In [63]:
# O método Heat Map do Folium aceita os dados em lista de pontos ou numpay arrays como latitude e longitude 
heat_data = list(df.values)
heat_data[:10]

[array([ -8.0694, -37.2684]),
 array([ -3.1019, -60.025 ]),
 array([  7.7872, -75.5331]),
 array([-31.9745, -60.916 ]),
 array([-41.4693, -72.9424]),
 array([-19.7609, -44.3137]),
 array([-22.0175, -47.8908]),
 array([-18.8564, -41.9547]),
 array([ 10.4829, -66.9036]),
 array([ -7.3577, -35.7849])]

In [64]:
# Adicionar o map para o heat map no qual passamos a lista de numpy array
m = folium.Map([-23.6100596,-46.6973898], zoom_start=2, tiles='cartodbpositron')
HeatMap(heat_data).add_to(m)
m

In [65]:
# Alterar o gradiente de cores. Esse parametro funciona como dicionário.
gradient = {
    '0.0': 'blue',
    '1': 'red'
}
m = folium.Map([-23.6100596,-46.6973898], zoom_start=2, tiles='cartodbpositron')
HeatMap(heat_data, gradient=gradient).add_to(m)
m

In [68]:
# Adicionar outras cores ao dicionário. 
gradient = {
    '0': 'Black',
    '0.4': 'Purple',
    '0.6': 'Red',
    '0.8': 'Yellow',
    '1': 'White'
}
m = folium.Map([-23.6100596,-46.6973898], zoom_start=2, tiles='cartodbpositron')
HeatMap(heat_data, gradient=gradient).add_to(m)
m

ANIMAÇÃO

In [69]:
# Filtrar dados
df_2019 = acled[acled['year'] == 2019]

In [70]:
# Ler colunas específicas depois de filtrados 
df_2019_latlon = df_2019[['latitude', 'longitude', 'event_date']] #as primeiras são as coordenadas e a terceira é o "peso para a animação
df_2019_latlon.head()

latitude  longitude        event_date
0   -8.0694   -37.2684  31 December 2019
1   -3.1019   -60.0250  31 December 2019
2    7.7872   -75.5331  31 December 2019
3  -31.9745   -60.9160  31 December 2019
4  -41.4693   -72.9424  31 December 2019

In [79]:
# Converter 'event_date' para função de tempo ('heat') 
df_2019_latlon['heat'] = pd.to_datetime(df_2019_latlon['event_date'])
df_2019_latlon.head()

C:\Users\iribarre\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


latitude  longitude        event_date       heat
0   -8.0694   -37.2684  31 December 2019 2019-12-31
1   -3.1019   -60.0250  31 December 2019 2019-12-31
2    7.7872   -75.5331  31 December 2019 2019-12-31
3  -31.9745   -60.9160  31 December 2019 2019-12-31
4  -41.4693   -72.9424  31 December 2019 2019-12-31

In [82]:
# extrair o número do mês que será usado como peso na animação
df_2019_latlon['month'] = df_2019_latlon['heat'].dt.month

C:\Users\iribarre\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [83]:
# Seleciona apenas os dados que serão usados
data = df_2019_latlon[['latitude', 'longitude', 'month']]
data.sample(10)

latitude  longitude  month
8168   -22.8872   -42.0262      8
15896  -22.3848   -41.7832      4
3668   -17.3895   -66.1568     11
16539  -27.0524   -49.5188      3
5186   -11.0267   -68.7692     10
1170   -25.3468   -57.6065     12
4466   -34.9856   -71.2398     10
5773     7.3471   -61.8268     10
8280     8.2950   -62.7191      8
7960     4.6023   -61.1103      9

In [90]:
# Definir iterações sobre as linhas e então sobre o peso
heat_data = [[[row['latitude'],row['longitude']] for index, row in data[data['month'] == i].iterrows()] for i in range(0,13)]

In [91]:
# Passar heat data para o heat mapa usando o metodo de tempo como volume (?)
m = folium.Map([-23.6100596,-46.6973898], zoom_start=2, tiles='cartodbpositron')
HeatMapWithTime(heat_data, auto_play=True,max_opacity=0.8).add_to(m)
m